server:
  port: 18082
spring:
  application:
    name: user-consumer # 应用名称,多个同名的服务就是一个集群

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka # 注册中心地址
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

## 配置熔断策略：
#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        # 强制打开熔断器 默认false关闭的。测试配置是否生效
#        forceOpen: false
#        # 触发熔断错误比例阈值，默认值50%
#        errorThresholdPercentage: 50
#        # 熔断后休眠时长，默认值5秒
#        sleepWindowInMilliseconds: 10000
#        # 熔断触发最小请求次数，默认值是20
#        requestVolumeThreshold: 10
#      execution:
#        isolation:
#          thread:
#            # 熔断超时设置，默认为1秒
#            timeoutInMilliseconds: 5000
# 修改服务地址轮询策略，默认是轮询，配置之后变随机

user-provider:
  ribbon:
    #轮询
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    ConnectTimeout: 10000 # 连接超时时间
    ReadTimeout: 2000 # 数据读取超时时间
    MaxAutoRetries: 1 # 最大重试次数(第一个服务)
    MaxAutoRetriesNextServer: 0 # 最大重试下一个服务次数(集群的情况才会用到)
    OkToRetryOnAllOperations: false # 无论是请求超时或者socket read timeout都进行重试

feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能